# Site wide configuration

title: Ivan Proskuryakov
description: "Young, energetic, purposeful, always in touch with cutting edge technologies."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Ivan Proskuryakov
  web: https://github.com/ivanproskuryakov
  email: volgodark@gmail.com
  twitter: iproskuryakov
  bio: "Young, energetic, purposeful, always in touch with cutting edge technologies."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]